NUMPY

In [1]:
import numpy as np
n1 = np.array([10, 20, 30, 40])
n1

array([10, 20, 30, 40])

In [2]:
import numpy as np
n2 = np.zeros((3,2))
n2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
n3 = np.full((4,5), 7)
n3

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [4]:
n4 = np.arange(10, 31)
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [5]:
n5 = np.arange(10, 31, 2)
n5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [6]:
n5 = np.random.randint(1, 300, 7)
n5

array([271, 133, 196, 127, 176,   5,  76], dtype=int32)

In [7]:
n6 = np.array([[1,2,3],[4,5,6]])
n6.shape

(2, 3)

In [8]:
n7 = np.array([10, 20, 30])
n8 = np.array([40, 50, 60])

np.vstack((n7, n8))


array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
n9 = np.array([10, 20, 30])
n10 = np.array([40, 50, 60])
np.hstack((n7, n8))

array([10, 20, 30, 40, 50, 60])

In [10]:
n11 = np.array([10, 20, 30])
n12 = np.array([40, 50, 60])
np.column_stack((n7, n8))


array([[10, 40],
       [20, 50],
       [30, 60]])

In [11]:
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,3,2,1])
np.sum((n1,n2))

np.int64(20)

In [12]:
import numpy as np
n1=np.array([10,20,30,40])
np.mean(n1)

np.float64(25.0)

In [13]:
import numpy as np
n1=np.array([10,20,30,40])
np.std(n1)


np.float64(11.180339887498949)

In [14]:
import numpy as np
n1=np.array([10,20,30,40])
np.median(n1)

np.float64(25.0)

In [15]:
n1

array([10, 20, 30, 40])

In [16]:
n1.transpose()

array([10, 20, 30, 40])